import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import { ContractProvider } from "./lib/ContractContext";
import "./styles.css";
import Providers from "./providers/privyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{'backgroundColor':'#0B132B'}}>
      <body className={inter.className}>
          <Providers>
            <ContractProvider>
                  {children}
            </ContractProvider>
          </Providers>
      </body>
    </html>
  );
}
